USE EMPLOYEE_DB;

DELIMITER &&
DROP PROCEDURE IF EXISTS `UpdateSalaryHike`;

CREATE PROCEDURE `UpdateSalaryHike`()
BEGIN

CREATE TABLE IF NOT EXISTS hike2022(
HIKE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
EMPIDFK INT,
FirstName VARCHAR(100),
LASTNAME VARCHAR(100),
GENDER VARCHAR(100),
WEIGHTINKG DOUBLE,
LASTHIKE VARCHAR(100),
LASTSALARY VARCHAR(100),
NEWHIKE VARCHAR(100),
NEWSALARY VARCHAR(100),
CONSTRAINT EMPFK1 FOREIGN KEY (EMPIDFK) REFERENCES person(Emp_ID)
);
TRUNCATE TABLE hike2022;
INSERT INTO hike2022(EMPIDFK,FirstName,LASTNAME,GENDER,WEIGHTINKG,LASTHIKE,LASTSALARY,NEWHIKE,NEWSALARY) 
SELECT
EMP_ID,FIRST_NAME,LAST_NAME,GENDER,WEIGHT_IN_KGS,LAST_HIKE,SALARY,CONCAT(SUBSTR(LAST_HIKE FROM 1 FOR CHAR_LENGTH(LAST_HIKE)-1)+2,'%') AS NEWHIKE,
ROUND(SALARY*(1+(SUBSTR(LAST_HIKE FROM 1 FOR CHAR_LENGTH(LAST_HIKE)-1)+2)/100),2) AS NEWSALARY
FROM person
WHERE WEIGHT_IN_KGS < 50;

END&&
DELIMITER ;

CALL UpdateSalaryHike();
SELECT * FROM hike2022;
